[[constraint]]
  name = "github.com/gorilla/context"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/mux"

[[constraint]]
  name = "github.com/pmezard/go-difflib"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"
